source 'http://rubygems.org'

ruby '1.9.2'

#gem 'rails', '4.0.0'
gem 'rails', '3.1.0'

# Rake 0.9 breaks some Rails things with ruby 1.9
gem "rake", "10.1.0"
#gem "rake", "0.9.2.2"

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

group :development, :test do
	# gem 'sqlite3'
	# gem 'mysql2'
	# To use debugger
  gem 'pg'
	gem 'ruby-debug19'
end

#
## Searching
#gem 'thinking-sphinx', '2.0.11'

# Needed for scraping
gem 'htmlentities'
gem 'nokogiri'
#gem 'mechanize'
gem 'diamond-mechanize', '2.4'
gem 'watir-webdriver'
gem 'json'

#gem 'protected_attributes'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  #gem 'sass-rails'
  #gem 'coffee-rails'
  gem 'multi_json', "~> 1.3"
  gem 'uglifier'
  gem 'yui-compressor'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# for Heroku
group :production do
  #gem 'flying-sphinx'
  gem 'pg'
  gem 'thin'
 # gem 'flying-sphinx',   '0.6.2'
end

gem 'chronic'

# For logging in
gem 'devise'
# Facebook Connect
gem 'omniauth-facebook'
gem 'koala'

# Performance
gem 'newrelic_rpm'

# Endless Page
gem 'kaminari'

gem 'devise-encryptable'

gem 'bootstrap-sass', '2.1'

gem 'execjs', '1.4.0'